package com.ccsu.community.mapper;

import com.ccsu.community.model.LikeUser;
import com.ccsu.community.model.LikeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    long countByExample(LikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int deleteByExample(LikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int insert(LikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int insertSelective(LikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    List<LikeUser> selectByExampleWithRowbounds(LikeUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    List<LikeUser> selectByExample(LikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    LikeUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") LikeUser record, @Param("example") LikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int updateByExample(@Param("record") LikeUser record, @Param("example") LikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int updateByPrimaryKeySelective(LikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_user
     *
     * @mbg.generated Mon Apr 13 01:12:05 CST 2020
     */
    int updateByPrimaryKey(LikeUser record);
}