package com.ccsu.community.mapper;

import com.ccsu.community.model.Verify;
import com.ccsu.community.model.VerifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    long countByExample(VerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int deleteByExample(VerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int insert(Verify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int insertSelective(Verify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    List<Verify> selectByExampleWithRowbounds(VerifyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    List<Verify> selectByExample(VerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    Verify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Verify record, @Param("example") VerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int updateByExample(@Param("record") Verify record, @Param("example") VerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int updateByPrimaryKeySelective(Verify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sun Apr 19 02:40:37 CST 2020
     */
    int updateByPrimaryKey(Verify record);
}